export enum Papel {
  DIRETOR = 'DIRETOR',
  DIRETOR_FOTOGRAFIA = 'DIRETOR_FOTOGRAFIA',
  SONOPLASTA = 'SONOPLASTA',
  EDITOR = 'EDITOR',
  ROTEIRISTA = 'ROTEIRISTA',
  EFEITOS_VISUAIS = 'EFEITOS_VISUAIS',
}
